In [1]:
import tensorflow as tf
import tensorflow_text as text

In [2]:
saved_model_path = 'bert_saved_model'
loaded_model = tf.saved_model.load(saved_model_path)
infer = loaded_model.signatures["serving_default"]

In [3]:
examples = [
    "Pfizer, Moderna Test Vaccines Against New Coronavirus Strain",
    "India Invites Bids To Sell Entire Stake In Shipping Corporation",
    "Kartik Aaryan to make his music video debut with 'Nachunga Aisa",
    "The Geminid meteor shower can be seen in the sky tonight without any binoculars",
]

In [4]:
results = infer(tf.constant(examples))
serving_results = list(tf.argmax(results['classifier'], axis=-1))

In [5]:
serving_results

[<tf.Tensor: shape=(), dtype=int64, numpy=2>,
 <tf.Tensor: shape=(), dtype=int64, numpy=0>,
 <tf.Tensor: shape=(), dtype=int64, numpy=1>,
 <tf.Tensor: shape=(), dtype=int64, numpy=3>]